name: openwrt 19.07

# Copyright (c) 2020, Chuck <fanck0605@qq.com>
#
# 警告:
# 对着屏幕的哥们, 我们允许你使用此脚本, 但不允许你抹去作者的信息, 请保留这段话.
# 你可以随意使用本脚本的代码, 但请注明出处.
#

on:
  push:
    branches:
      - openwrt-19.07
    paths:
      - '.github/workflows/main.yml'
      - 'patches/**'
      - 'config_rk3328'
      - 'nanopi-r2_linux_defconfig'
      - 'CHANGELOG.md'
  schedule:
    - cron: '00 18 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: openwrt-19.07

      # refer to klever1988/nanopi-openwrt and soffchen/NanoPi-R2S
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          git config --global user.name "Chuck"
          git config --global user.email "fanck0605@qq.com"

      - name: Install Repo
        run: |
          rm -rf repo
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          rm -rf repo

      - name: Initialization Source
        run: |
          rm -rf rk3328 && mkdir rk3328 && cd rk3328
          repo init -u https://github.com/fanck0605/friendlywrt_mainfests -b openwrt-19.07 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c --no-clone-bundle -j8

      - name: Update OpenWrt Feeds
        run: |
          cd rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # default version contains some bug
      - name: Upgrade Argon Theme
        run: |
          cd rk3328/friendlywrt/package/ctcgfw
          rm -rf luci-theme-argon
          git clone --depth 1 -b 19.07 https://github.com/jerrykuku/luci-theme-argon.git

      - name: Install R2s Flasher
        run: |
          mkdir -p rk3328/friendlywrt/package/songchenwen
          git clone --depth 1 https://github.com/songchenwen/nanopi-r2s.git r2sflasher
          cp -a r2sflasher/luci-app-r2sflasher rk3328/friendlywrt/package/songchenwen/
          rm -rf r2sflasher

      - name: Patch Openwrt Firewall
        run: |
          cd rk3328/friendlywrt
          mkdir package/network/config/firewall/patches
          wget -P package/network/config/firewall/patches/ https://github.com/LGA1150/fullconenat-fw3-patch/raw/master/fullconenat.patch
          cd feeds/luci
          wget -O- https://github.com/LGA1150/fullconenat-fw3-patch/raw/master/luci.patch | git apply

      - name: Install UPX
        run: |
          ln -s /usr/bin/upx-ucl rk3328/friendlywrt/staging_dir/host/bin/upx

      # refer to klever1988/nanopi-openwrt, modified by Chuck <fanck0605@qq.com>
      - name: Patch Rockchip Kernel
        run: |
          rm -rf openwrt
          git clone --depth 1 -b master https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/generic/backport-5.4
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/generic/pending-5.4
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/generic/hack-5.4
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/octeontx/patches-5.4
          cp -a ./target/linux/generic/files/* ../rk3328/kernel/
          cd ../ && rm -rf openwrt

      # refer to klever1988/nanopi-openwrt, modified by Chuck <fanck0605@qq.com>
      - name: Enable Kernel Futures
        run: |
          cd rk3328/kernel/
          wget -O net/netfilter/xt_FULLCONENAT.c https://raw.githubusercontent.com/Chion82/netfilter-full-cone-nat/master/xt_FULLCONENAT.c
          git apply ../../patches/001-kernel-add-full_cone_nat.patch
          cat ../../nanopi-r2_linux_defconfig > ./arch/arm64/configs/nanopi-r2_linux_defconfig

      - name: Customize Configuration Files
        run: |
          cat config_rk3328 > rk3328/configs/config_rk3328
          #cat config_usb-net >> rk3328/configs/config_rk3328

      # 如果不喜欢互换, 直接注释即可
      - name: Swap wan and lan
        run: |
          cd rk3328/friendlywrt
          git apply ../../patches/003-openwrt-swap-wan-and-lan.patch

      - name: Build FriendlyWrt
        run: |
          cd rk3328
          ./build.sh nanopi_r2s.mk

      - name: Fix FriendlyWrt rootfs owner and group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -P ${lodev} rk3328/out/FriendlyWrt*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount ${lodev}p1 /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d ${lodev}

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          gzip rk3328/out/FriendlyWrt*.img
          cp rk3328/out/FriendlyWrt*.img.gz ./artifact/

      # 保存交叉编译配置, 需要先设置平台
      - name: Save Configurations
        run: |
          cd rk3328/friendlywrt
          ./scripts/diffconfig.sh > ../../artifact/config-lite
          cp .config ../../artifact/config-full
          cd ../kernel
          export PATH=/opt/FriendlyARM/toolchain/6.4-aarch64/bin/:$PATH
          export CROSS_COMPILE='aarch64-linux-gnu-'
          export ARCH=arm64
          make savedefconfig
          cp .config ../../artifact/kconfig-full
          cp defconfig ../../artifact/kconfig-lite

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt
          path: ./artifact/
